# Generated by Django 4.0 on 2021-12-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('langauge', models.CharField(max_length=100)),
                ('edition', models.TextField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='book/images/')),
            ],
        ),
    ]
